# Generated by Django 3.1.3 on 2020-11-09 12:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('county', models.CharField(max_length=150)),
                ('town', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('sale_type', models.CharField(choices=[('for sale ', 'For Sale'), ('for rent ', 'For Rent')], default='for rent ', max_length=50)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('home_type', models.CharField(choices=[('apartment', 'Apartments'), ('bedsitter', 'Bedsitters'), ('commercialProperties', 'Commercial Properties'), (' house ', 'Houses'), ('single', 'Singles'), (' bedroom', 'Bedroom'), ('land', 'Land')], default='bedsitter', max_length=50)),
                ('square_foot', models.IntegerField()),
                ('open_house', models.BooleanField(default=False)),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y%m%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtors')),
            ],
        ),
    ]
