# Generated by Django 3.1.3 on 2020-11-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='sale_type',
            field=models.CharField(choices=[('for sale ', 'For Sale'), ('for rent ', 'For Rent')], default='for sale ',
                                   max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
